# Site settings
title: Jekyll Prose
email: mailbox@lvdesign.com.fr
description: Jekyll avec Prose 
baseurl: /jekyllProse


twitter_username: lvdesign
github_username:  lvdesign

# Build settings
markdown: kramdown
highlighter: rouge
