# Site settings
title: Jekyll Prose
email: mailbox@lvdesign.com.fr
description: Jekyll avec Prose 
baseurl: /jekyllProse

#config
prose:
    ignore:
        - index.md
        - _config.yml
    siteurl: 'http://lvdesign.github.io/jekyllProse'
    rooturl: '_posts'
    
    media: 'media'
    metadata:
    _posts:
        - name: "layout"
            field:
                element: "hidden"
                value: "post"
        
        - name: "categories"
            field:
                elements: "multiselect"
                label: "Add categorie"
                placeholder: "Add Categories"
                alterable: true
            
        - name: "title"
            field:
                element: "text"
                label: "title"
        
        - name: "Textarea"
            field:
                element: "textarea"
                label: "text"






twitter_username: lvdesign
github_username:  lvdesign

# Build settings
markdown: kramdown
highlighter: rouge
